# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "develop, master" ]
  pull_request:
    branches: [ "develop, master" ]

jobs:
  build:

    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        node-version: [14.x, 16.x, 18.x]
#        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x #${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '14.x' #${{ matrix.node-version }}
    - run: npm ci #stands for npm clean install. 
    - run: npm run test-backend
      env:
        CI: true
        MONGODB_URL_TEST: mongodb+srv://project_tester:project_tester_123@cluster0.lpmewey.mongodb.net/GroupProjectTesting?retryWrites=true&w=majority
        PORT: 5001
        SECRET_TOKEN: testingsecret
